version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16
    environment:
      PORT: 9000
      MONGO_CONNECTION_STRING: mongodb://${MONGO_USERNAME:-DEFAULT_MONGO_USERNAME}:${MONGO_PASSWORD:-DEFAULT_MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE:-reaxpresst}?authSource=admin&authMechanism=SCRAM-SHA-256&readPreference=primary&ssl=false

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE:-reaxpresst}
      MONGO_USERNAME: ${MONGO_USERNAME:-DEFAULT_MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-DEFAULT_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-reaxpresst}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-DEFAULT_MONGO_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-DEFAULT_MONGO_USERNAME}
    volumes:
      - mongodb-data:/data/db
      - ./dbInit:/docker-entrypoint-initdb.d
    command: [--auth]

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
volumes:
  mongodb-data: