version: '3.8'

x-global-env: &global-env
  MONGO_DATABASE: "${MONGO_INITDB_DATABASE:-reaxpresst}"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16
    environment:
      <<: *global-env

    secrets:
      - mongodb_password
      - mongodb_username
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      <<: *global-env
      MONGO_INITDB_DATABASE:  "${MONGO_INITDB_DATABASE:-admin}"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
secrets:
  mongodb_root_password:
    external: true
    name: "${MONGODB_ROOT_PASSWORD:-SUPERSECRET_MONGODB_ROOT_PASSWORD}"
  mongodb_root_username:
    external: true
    name: "${MONGODB_ROOT_USERNAME:-SUPERSECRET_MONGODB_ROOT_USERNAME}"
  mongodb_password:
    external: true
    name: "${MONGODB_PASSWORD:-SUPERSECRET_MONGODB_PASSWORD}"
  mongodb_username:
    external: true
    name: "${MONGODB_USERNAME:-SUPERSECRET_MONGODB_USERNAME}"


volumes:
  mongodb-data: